[conformer_gen]

[conformer_gen.RDKit_Settings]
NumberConformers = 500
MaximumIterations = 1000

[conformer_gen.CREST_Settings]
FileName = "CREST_input"
OptimisationLevel = "extreme"
GFNMethod = "gfn2"
NumCPUs = 10
RunTime = "24:00:00"
Email = "j.l.hobbs@leeds.ac.uk"