[conformer_gen]
FileName = "CREST_input"
NumCPUs = 10
RunTime = "24:00:00"
Email = "j.l.hobbs@leeds.ac.uk"

[conformer_gen.RDKit_Settings]
RDNumConf = 500
RDMaxIter = 1000

[conformer_gen.CREST_Settings]
CRESTOptLevel = "extreme"
CRESTMethod = "gfn2"

[conformer_gen.ORCA_Settings]
GOATMode = "GOAT"
GOATMethod = "gfn2"
GOATOptLevel = "Loose"
GOATUphill = "GFN2XTB"
ConvForced = "True"


[conformer_sort]
FileName = "CREST_input"
NumCPUs = 10
RunTime = "48:00:00"
Email = "j.l.hobbs@leeds.ac.uk"